[theme]
name = "gruvbox-dark"

[theme.overrides]
name = "gruvbox-dark"
[icons]
name = "material-nf"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

#[[block]]
# block = "pomodoro"
# length = 25
# break_length = 5
# message = "take a break"
# break_message = "back to work"
# notifier = "swaynag"


[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{ssid^10}"
device_format = "{icon}{ap}"
primary_only = true

[[block]]
block = "sound"
format = "{volume}"
on_click = "pavucontrol"
max_vol = 150

[[block]]
block = "backlight"
invert_icons = false

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
format_swap = "{swap_used_percents}"
interval = 10

#[[block]]
#block = "disk_space"
#path = "/"
#alert = 90.0
#warning = 70.0
#info_type = "used"
#interval = 1000
#format = "{icon} {available}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}"
inputs = ["Tctl"]

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
