[plugin]
deps = []

[[flavor.deps]]
use = "gosxrgxx/flexoki-dark"
rev = "28e1977"
hash = "9dbbb64ea20f9f1271c31951dea55c7b"

[[flavor.deps]]
use = "dangooddd/kanagawa"
rev = "1f3b3c7"
hash = "16ea0ff3583131788d57d5f7d34d0f61"
